version: "3.8"
name: 'test-product'

volumes:
  postgres_data:
  notused:
    driver: local

services:
  postgres:
    container_name: test-product-postgres
    image: postgres:15-alpine
    environment:
      #POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /home/postgres/pgdata
      POSTGRES_DB: test-product
      POSTGRES_PASSWORD: password
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres_data:/home/postgres/pgdata
    ports:
      - "5432:5432"
